plugins:
  - jekyll-feed
title: Legal Immigration   
author: codinggambit
email: jayraohere@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It is a description of a journey through many turns and tides.
  Some opinions on the whole legal immigration process

# social links
twitter_username: sanjaysrao88 # DO NOT include the @ character, or else the build will fail!
github_username:  codinggambit # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
